name: Deploy Seguro Galeria

on:
  push:
    branches:
      - main  # Certifique-se de que sua branch principal se chama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Injetar chaves de segurança
        run: |
          # Firebase Config
          sed -i "s/___FIREBASE_API_KEY___/${{ secrets.FIREBASE_API_KEY }}/g" index.html
          sed -i "s/___FIREBASE_AUTH_DOMAIN___/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g" index.html
          sed -i "s/___FIREBASE_PROJECT_ID___/${{ secrets.FIREBASE_PROJECT_ID }}/g" index.html
          sed -i "s/___FIREBASE_STORAGE_BUCKET___/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g" index.html
          sed -i "s/___FIREBASE_MESSAGING_SENDER_ID___/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g" index.html
          sed -i "s/___FIREBASE_APP_ID___/${{ secrets.FIREBASE_APP_ID }}/g" index.html
          sed -i "s/___FIREBASE_MEASUREMENT_ID___/${{ secrets.FIREBASE_MEASUREMENT_ID }}/g" index.html

          # EmailJS Config
          sed -i "s/___EMAILJS_PUBLIC_KEY___/${{ secrets.EMAILJS_PUBLIC_KEY }}/g" index.html

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with: