name: Deploy Seguro Galeria

on:
  push:
    branches:
      - main  # Verifique se o nome da sua branch é main ou master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Isso dá permissão extra para o deploy
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Injetar chaves de segurança
        run: |
          # Use o nome EXATO do seu arquivo (se for index.html, mude aqui)
          sed -i "s|___FIREBASE_API_KEY___|${{ secrets.FIREBASE_API_KEY }}|g" index.html
          sed -i "s|___FIREBASE_AUTH_DOMAIN___|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" index.html
          sed -i "s|___FIREBASE_PROJECT_ID___|${{ secrets.FIREBASE_PROJECT_ID }}|g" index.html
          sed -i "s|___FIREBASE_STORAGE_BUCKET___|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" index.html
          sed -i "s|___FIREBASE_MESSAGING_SENDER_ID___|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" index.html
          sed -i "s|___FIREBASE_APP_ID___|${{ secrets.FIREBASE_APP_ID }}|g" index.html
          sed -i "s|___EMAILJS_PUBLIC_KEY___|${{ secrets.EMAILJS_PUBLIC_KEY }}|g" index.html

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages